# x = list(map(int, input().split()))

# e = int(input())

# x.remove(e)
# print(x)
# ____________________________________________________________________________________________________________________________________________________________________________________________
# x = {"apple":100, "melon":200, "cherry":300}
# x.update({"melon":500})
# x.pop("cherry")
# print(x)
# ____________________________________________________________________________________________________________________________________________________________________________________________
# import turtle as t

# t.speed(100)
# t.bgcolor("skyblue")
# t.penup()
# t.goto(0,-50)
# t.pendown()
# t.color("white")
# t.begin_fill()
# t.circle(150)
# t.end_fill()
# t.penup()
# t.goto(0,0)
# t.pendown()
# t.color("orange")
# t.begin_fill()
# t.circle(30)
# t.end_fill()
# t.penup()
# t.goto(70,50)
# t.pendown()
# t.color("black")
# t.begin_fill()
# t.circle(30)
# t.end_fill()
# t.penup()
# t.goto(-70,50)
# t.pendown()
# t.color("black")
# t.begin_fill()
# t.circle(30)
# t.end_fill()
# t.penup()
# t.goto(0,-450)
# t.pendown()
# t.color("white")
# t.begin_fill()
# t.circle(200)
# t.end_fill()
# t.penup()
# t.goto(0,-400)
# t.pendown
# t.color("black")
# t.begin_fill()
# t.circle(10)
# t.end_fill()
# t.penup()
# t.goto(0,-300)
# t.pendown()
# t.color("black")
# t.begin_fill()
# t.circle(10)
# t.end_fill()
# t.penup()
# t.goto(0,-200)
# t.pendown()
# t.color("black")
# t.begin_fill()
# t.circle(10)
# t.end_fill()
# t.penup()
# t.goto(0,-100)
# t.pendown
# t.color("black")
# t.begin_fill()
# t.circle(10)
# t.end_fill()

# t.exitonclick()