# list_iter = ([1, 2 ,3].__iter__())
# print(list_iter.__next__())
# print(list_iter.__next__())
# print(list_iter.__next__())
# print(list_iter.__next__())

# list_iter = ("hello world".__iter__())
# print(list_iter.__next__())
# print(list_iter.__next__())
# print(list_iter.__next__())
# print(list_iter.__next__())